import { AuthNavbar } from "@/components/common/AuthNavbar";
import AuthWrapper from "@/wrappers/AuthWrapper";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper>
      <AuthNavbar />
      {children}
    </AuthWrapper>
  );
}
